services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tech-challenge-go-app
    restart: always
    ports:
      - "3003:8080"
    volumes:
      - ./:/app
    command: go run main.go
    environment:
      DB_HOST: mongodb
      DB_PORT: "27017"
      DB_USER: admin
      DB_PASSWORD: senha123
      DB_NAME: orders
      AWS_REGION: us-east-1
      AWS_USER_POOL_ID: us-east-1_3ofqHwfxr
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Porta padrão do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Usuário administrador
      MONGO_INITDB_ROOT_PASSWORD: senha123 # Senha do administrador
    volumes:
      - ./data:/data/db # Volume persistente para os dados
