apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-fase-4-order-nodeport
spec:
  type: NodePort
  selector:
    app: tech-challenge-fase-4-order-deployment
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
