apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-fase-4-order-secrets
stringData:
  DB_USER: "tech-challenge-fase-4-order"
  DB_PASSWORD: "tech-challenge-fase-4-order"
  DB_URI: "postgres://tech-challenge-fase-4-order:tech-challenge-fase-4-order@tech-challenge-fase-4-order-postgres/tech-challenge-fase-4-order?sslmode=disable"
