basePath: /api/v1
definitions:
  controllers.CheckoutRequest:
    properties:
      customer_id:
        type: string
      products_ids:
        items:
          type: string
        type: array
    type: object
  controllers.PreparationStatusUpdateRequest:
    properties:
      preparation_status:
        type: string
    type: object
  dtos.CheckoutDTO:
    properties:
      amount:
        type: number
      method:
        $ref: '#/definitions/dtos.MethodType'
      orderId:
        type: string
      paymentLink:
        type: string
    type: object
  dtos.MethodType:
    enum:
    - PIX
    - CREDIT_CARD
    type: string
    x-enum-varnames:
    - PIX
    - CREDIT_CARD
  dtos.OrderDisplayDTO:
    properties:
      createdAt:
        type: string
      customer_id:
        type: string
      items:
        items:
          $ref: '#/definitions/dtos.OrderItemDisplayDTO'
        type: array
      order_id:
        type: string
      preparation_status:
        type: string
    type: object
  dtos.OrderItemDisplayDTO:
    properties:
      product_name:
        type: string
      quantity:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /order/{order_id}/preparation-status:
    put:
      consumes:
      - application/json
      description: Update the preparation status for an order
      parameters:
      - description: Order Identification
        in: path
        name: order_id
        required: true
        type: string
      - description: Order Request Params
        in: body
        name: preparation_status_update
        required: true
        schema:
          $ref: '#/definitions/controllers.PreparationStatusUpdateRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: when bad request
          schema:
            type: string
      summary: Update order preparation status
      tags:
      - orders
  /order/checkout:
    post:
      consumes:
      - application/json
      description: make a checkout for an order
      parameters:
      - description: Checkout
        in: body
        name: checkout
        required: true
        schema:
          $ref: '#/definitions/controllers.CheckoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.CheckoutDTO'
        "400":
          description: when bad request
          schema:
            type: string
        "406":
          description: when invalid params or invalid object
          schema:
            type: string
      summary: Make an order checkout
      tags:
      - orders
  /order/display:
    get:
      consumes:
      - application/json
      description: Get order list for a display
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.OrderDisplayDTO'
            type: array
        "400":
          description: when bad request
          schema:
            type: string
      summary: Get order list
      tags:
      - orders
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
