// Code generated by mockery v2.49.0. DO NOT EDIT.

package queries

import (
	dtos "tech-challenge-fase-1/internal/core/dtos"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderDisplayListQueryInterface is an autogenerated mock type for the OrderDisplayListQueryInterface type
type MockOrderDisplayListQueryInterface struct {
	mock.Mock
}

type MockOrderDisplayListQueryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderDisplayListQueryInterface) EXPECT() *MockOrderDisplayListQueryInterface_Expecter {
	return &MockOrderDisplayListQueryInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *MockOrderDisplayListQueryInterface) Execute() ([]*dtos.OrderDisplayDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*dtos.OrderDisplayDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*dtos.OrderDisplayDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*dtos.OrderDisplayDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dtos.OrderDisplayDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderDisplayListQueryInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOrderDisplayListQueryInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockOrderDisplayListQueryInterface_Expecter) Execute() *MockOrderDisplayListQueryInterface_Execute_Call {
	return &MockOrderDisplayListQueryInterface_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockOrderDisplayListQueryInterface_Execute_Call) Run(run func()) *MockOrderDisplayListQueryInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderDisplayListQueryInterface_Execute_Call) Return(_a0 []*dtos.OrderDisplayDTO, _a1 error) *MockOrderDisplayListQueryInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderDisplayListQueryInterface_Execute_Call) RunAndReturn(run func() ([]*dtos.OrderDisplayDTO, error)) *MockOrderDisplayListQueryInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderDisplayListQueryInterface creates a new instance of MockOrderDisplayListQueryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderDisplayListQueryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderDisplayListQueryInterface {
	mock := &MockOrderDisplayListQueryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
